services:
  api:
    image: piyushjain31/aeo-audit-tool:latest
    container_name: fastapi
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env.production
    depends_on:
      redis:
        condition: service_started
    volumes:
      - ./logs:/app/logs

  worker:
    image: piyushjain31/aeo-audit-tool:latest
    container_name: celery-worker
    command: celery -A app.worker.celery_app worker --loglevel=info --concurrency=${WORKER_CONCURRENCY_LIMIT:-1}
    env_file:
      - .env.production
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
