"""create_brand_mentions_table

Revision ID: b76887ae16ea
Revises: f64946128996
Create Date: 2026-06-27 19:39:15.150424

"""

from typing import Sequence, Union

from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b76887ae16ea"
down_revision: Union[str, Sequence[str], None] = "f64946128996"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

mention_type_enum = postgresql.ENUM(
    "neutral",
    "recommendation",
    "comparison",
    "warning",
    "product_listing",
    name="mention_type",
    create_type=False,
)

sentiment_type_enum = postgresql.ENUM(
    "positive",
    "neutral",
    "negative",
    "mixed",
    "unknown",
    name="sentiment_type",
    create_type=False,
)

recommendation_strength_enum = postgresql.ENUM(
    "strong",
    "medium",
    "weak",
    "none",
    "unknown",
    name="recommendation_strength",
    create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brand_mentions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_batch_id", sa.UUID(), nullable=False),
        sa.Column("prompt_run_id", sa.UUID(), nullable=False),
        sa.Column("observation_id", sa.UUID(), nullable=False),
        sa.Column("extraction_result_id", sa.UUID(), nullable=False),
        sa.Column("prompt_id", sa.UUID(), nullable=False),
        sa.Column("platform_id", sa.UUID(), nullable=False),
        sa.Column("brand_name_snapshot", sa.Text(), nullable=False),
        sa.Column("mention_text", sa.Text(), nullable=False),
        sa.Column("mention_context", sa.Text(), nullable=True),
        sa.Column("character_start", sa.Integer(), nullable=True),
        sa.Column("character_end", sa.Integer(), nullable=True),
        sa.Column(
            "mention_type",
            mention_type_enum, 
            server_default="neutral",
            nullable=False,
        ),
        sa.Column(
            "sentiment",
            sentiment_type_enum,
            server_default="unknown",
            nullable=False,
        ),
        sa.Column(
            "is_recommended",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "recommendation_strength",
            recommendation_strength_enum, 
            server_default="unknown",
            nullable=False,
        ),
        sa.Column(
            "confidence_score",
            sa.Numeric(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["extraction_result_id"], ["extraction_results.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"], ["ai_observations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["platform_id"], ["ai_platforms.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["brand_projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["prompt_id"], ["prompts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["prompt_run_id"], ["prompt_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["run_batch_id"], ["run_batches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_brand_mentions_extraction_result_id",
        "brand_mentions",
        ["extraction_result_id"],
        unique=False,
    )
    op.create_index(
        "ix_brand_mentions_is_recommended",
        "brand_mentions",
        ["is_recommended"],
        unique=False,
    )
    op.create_index(
        "ix_brand_mentions_mention_type",
        "brand_mentions",
        ["mention_type"],
        unique=False,
    )
    op.create_index(
        "ix_brand_mentions_observation_id",
        "brand_mentions",
        ["observation_id"],
        unique=False,
    )
    op.create_index(
        "ix_brand_mentions_organization_id",
        "brand_mentions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_brand_mentions_platform_id", "brand_mentions", ["platform_id"], unique=False
    )
    op.create_index(
        "ix_brand_mentions_project_id", "brand_mentions", ["project_id"], unique=False
    )
    op.create_index(
        "ix_brand_mentions_prompt_id", "brand_mentions", ["prompt_id"], unique=False
    )
    op.create_index(
        "ix_brand_mentions_prompt_run_id",
        "brand_mentions",
        ["prompt_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_brand_mentions_run_batch_id",
        "brand_mentions",
        ["run_batch_id"],
        unique=False,
    )
    op.create_index(
        "ix_brand_mentions_sentiment", "brand_mentions", ["sentiment"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_brand_mentions_sentiment", table_name="brand_mentions")
    op.drop_index("ix_brand_mentions_run_batch_id", table_name="brand_mentions")
    op.drop_index("ix_brand_mentions_prompt_run_id", table_name="brand_mentions")
    op.drop_index("ix_brand_mentions_prompt_id", table_name="brand_mentions")
    op.drop_index("ix_brand_mentions_project_id", table_name="brand_mentions")
    op.drop_index("ix_brand_mentions_platform_id", table_name="brand_mentions")
    op.drop_index("ix_brand_mentions_organization_id", table_name="brand_mentions")
    op.drop_index("ix_brand_mentions_observation_id", table_name="brand_mentions")
    op.drop_index("ix_brand_mentions_mention_type", table_name="brand_mentions")
    op.drop_index("ix_brand_mentions_is_recommended", table_name="brand_mentions")
    op.drop_index("ix_brand_mentions_extraction_result_id", table_name="brand_mentions")
    op.drop_table("brand_mentions")
    # ### end Alembic commands ###
