"""add email to jobs

Revision ID: e3f2ece0a4b1
Revises: 0a577c9a5737
Create Date: 2026-06-23 08:31:26.925595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f2ece0a4b1'
down_revision: Union[str, Sequence[str], None] = '0a577c9a5737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('email', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'email')
    # ### end Alembic commands ###
