"""create_prompt_sets_table

Revision ID: f453c915f215
Revises: 15ef51c00a52
Create Date: 2026-06-27 18:28:56.091420

"""

from typing import Sequence, Union

from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f453c915f215"
down_revision: Union[str, Sequence[str], None] = "15ef51c00a52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

prompt_sets_status_enum = postgresql.ENUM(
    "draft", "active", "archived", name="prompt_set_status", create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_sets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "status",
            prompt_sets_status_enum,
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "prompt_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["brand_projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_prompt_sets_created_by_user_id",
        "prompt_sets",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_prompt_sets_organization_id",
        "prompt_sets",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_prompt_sets_project_id", "prompt_sets", ["project_id"], unique=False
    )
    op.create_index(
        "ix_prompt_sets_project_name_version",
        "prompt_sets",
        ["project_id", "name", "version"],
        unique=True,
    )
    op.create_index("ix_prompt_sets_status", "prompt_sets", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_prompt_sets_status", table_name="prompt_sets")
    op.drop_index("ix_prompt_sets_project_name_version", table_name="prompt_sets")
    op.drop_index("ix_prompt_sets_project_id", table_name="prompt_sets")
    op.drop_index("ix_prompt_sets_organization_id", table_name="prompt_sets")
    op.drop_index("ix_prompt_sets_created_by_user_id", table_name="prompt_sets")
    op.drop_table("prompt_sets")
    # ### end Alembic commands ###
