"""create_citations_table

Revision ID: f64946128996
Revises: 249a0ea3d58b
Create Date: 2026-06-27 19:34:55.844410

"""

from typing import Sequence, Union

from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f64946128996"
down_revision: Union[str, Sequence[str], None] = "249a0ea3d58b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

source_category_enum = postgresql.ENUM(
    "owned",
    "competitor",
    "marketplace",
    "publisher",
    "forum",
    "social",
    "unknown",
    name="source_category",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "citations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_batch_id", sa.UUID(), nullable=False),
        sa.Column("prompt_run_id", sa.UUID(), nullable=False),
        sa.Column("observation_id", sa.UUID(), nullable=False),
        sa.Column("extraction_result_id", sa.UUID(), nullable=False),
        sa.Column("prompt_id", sa.UUID(), nullable=False),
        sa.Column("platform_id", sa.UUID(), nullable=False),
        sa.Column("competitor_id", sa.UUID(), nullable=True),
        sa.Column("citation_index", sa.Integer(), nullable=False),
        sa.Column("citation_marker", sa.Text(), nullable=True),
        sa.Column("cited_url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("cited_domain", sa.Text(), nullable=False),
        sa.Column("root_domain", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("citation_context", sa.Text(), nullable=True),
        sa.Column(
            "is_owned_domain",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_competitor_domain",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "source_category",
            source_category_enum,
            server_default="unknown",
            nullable=False,
        ),
        sa.Column(
            "confidence_score",
            sa.Numeric(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competitor_id"], ["competitors.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["extraction_result_id"], ["extraction_results.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"], ["ai_observations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["platform_id"], ["ai_platforms.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["brand_projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["prompt_id"], ["prompts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["prompt_run_id"], ["prompt_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["run_batch_id"], ["run_batches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_citations_citation_index", "citations", ["citation_index"], unique=False
    )
    op.create_index(
        "ix_citations_cited_domain", "citations", ["cited_domain"], unique=False
    )
    op.create_index(
        "ix_citations_competitor_id", "citations", ["competitor_id"], unique=False
    )
    op.create_index(
        "ix_citations_extraction_result_id",
        "citations",
        ["extraction_result_id"],
        unique=False,
    )
    op.create_index(
        "ix_citations_is_competitor_domain",
        "citations",
        ["is_competitor_domain"],
        unique=False,
    )
    op.create_index(
        "ix_citations_is_owned_domain", "citations", ["is_owned_domain"], unique=False
    )
    op.create_index(
        "ix_citations_observation_id", "citations", ["observation_id"], unique=False
    )
    op.create_index(
        "ix_citations_organization_id", "citations", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_citations_platform_id", "citations", ["platform_id"], unique=False
    )
    op.create_index(
        "ix_citations_project_id", "citations", ["project_id"], unique=False
    )
    op.create_index("ix_citations_prompt_id", "citations", ["prompt_id"], unique=False)
    op.create_index(
        "ix_citations_prompt_run_id", "citations", ["prompt_run_id"], unique=False
    )
    op.create_index(
        "ix_citations_root_domain", "citations", ["root_domain"], unique=False
    )
    op.create_index(
        "ix_citations_run_batch_id", "citations", ["run_batch_id"], unique=False
    )
    op.create_index(
        "ix_citations_source_category", "citations", ["source_category"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_citations_source_category", table_name="citations")
    op.drop_index("ix_citations_run_batch_id", table_name="citations")
    op.drop_index("ix_citations_root_domain", table_name="citations")
    op.drop_index("ix_citations_prompt_run_id", table_name="citations")
    op.drop_index("ix_citations_prompt_id", table_name="citations")
    op.drop_index("ix_citations_project_id", table_name="citations")
    op.drop_index("ix_citations_platform_id", table_name="citations")
    op.drop_index("ix_citations_organization_id", table_name="citations")
    op.drop_index("ix_citations_observation_id", table_name="citations")
    op.drop_index("ix_citations_is_owned_domain", table_name="citations")
    op.drop_index("ix_citations_is_competitor_domain", table_name="citations")
    op.drop_index("ix_citations_extraction_result_id", table_name="citations")
    op.drop_index("ix_citations_competitor_id", table_name="citations")
    op.drop_index("ix_citations_cited_domain", table_name="citations")
    op.drop_index("ix_citations_citation_index", table_name="citations")
    op.drop_table("citations")
    # ### end Alembic commands ###
